#!/bin/bash
# memusage-champsim — LD_PRELOAD-based allocation trace tool
# with optional ChampSim format output (-c FILE)
# Copyright (C) 1999-2026 Free Software Foundation, Inc.
# Part of the GNU C Library.
#
# Modified to support -c,--champsim-trace=FILE for 40-byte malloc_instr output.

memusageso='./libmemusage-champsim.so'
TEXTDOMAIN=libc

do_usage() {
  printf >&2 "Try \`%s --help' or \`%s --usage' for more information.\n" memusage memusage
  exit 1
}

do_missing_arg() {
  printf >&2 "%s: option '%s' requires an argument\n" memusage "$1"
  do_usage
}

do_help() {
  echo "Usage: memusage [OPTION]... PROGRAM [PROGRAMOPTION]...
Profile memory usage of PROGRAM.

   -n,--progname=NAME     Name of the program file to profile
   -p,--png=FILE          Generate PNG graphic and store it in FILE
   -d,--data=FILE         Generate binary data file and store it in FILE
   -u,--unbuffered        Don't buffer output
   -b,--buffer=SIZE       Collect SIZE entries before writing them out
      --no-timer          Don't collect additional information through timer
   -m,--mmap              Also trace mmap & friends
   -c,--champsim-trace=FILE  Also output ChampSim malloc trace format

   -?,--help              Print this help and exit
      --usage             Give a short usage message
   -V,--version           Print version information and exit

 The following options only apply when generating graphical output:
   -t,--time-based        Make graph linear in time
   -T,--total             Also draw graph of total memory use
      --title=STRING      Use STRING as title of the graph
   -x,--x-size=SIZE       Make graphic SIZE pixels wide
   -y,--y-size=SIZE       Make graphic SIZE pixels high

"
  exit 0
}

buffer=
data=
memusagestat_args=
notimer=
png=
progname=
tracemmap=
mtrace=

while test $# -gt 0; do
  case "$1" in
  -V | --version) echo "memusage-champsim"; exit 0 ;;
  -\? | --help) do_help ;;
  --usage) echo "Syntax: ... [--champsim-trace=FILE] PROGRAM"; exit 0 ;;
  -n | --progname) shift; progname="$1" ;;
  --progname=*) progname=${1##*=} ;;
  -p | --png) shift; png="$1" ;;
  --png=*) png=${1##*=} ;;
  -d | --data) shift; data="$1" ;;
  --data=*) data=${1##*=} ;;
  -u | --unbuffered) buffer=1 ;;
  -b | --buffer) shift; buffer="$1" ;;
  --buffer=*) buffer=${1##*=} ;;
  --no-timer) notimer=yes ;;
  -c | --champsim-trace) shift; mtrace="$1" ;;
  --champsim-trace=*) mtrace=${1##*=} ;;
  -m | --mmap) tracemmap=yes ;;
  -t | --time-based) memusagestat_args="$memusagestat_args -t" ;;
  -T | --total) memusagestat_args="$memusagestat_args -T" ;;
  --title) shift; memusagestat_args="$memusagestat_args -s $1" ;;
  --title=*) memusagestat_args="$memusagestat_args -s ${1##*=}" ;;
  -x | --x-size) shift; memusagestat_args="$memusagestat_args -x $1" ;;
  --x-size=*) memusagestat_args="$memusagestat_args -x ${1##*=}" ;;
  -y | --y-size) shift; memusagestat_args="$memusagestat_args -y $1" ;;
  --y-size=*) memusagestat_args="$memusagestat_args -y ${1##*=}" ;;
  --) shift; break ;;
  --*) echo >&2 "memusage: unrecognized option \`$1'"; do_usage ;;
  *) break ;;
  esac
  shift
done

if test $# -eq 0; then echo >&2 "No program name given"; do_usage; fi

add_env="LD_PRELOAD=$memusageso"

datafile=
if test -n "$data"; then datafile="$data"
elif test -n "$png"; then
  datafile=$(mktemp -t memusage.XXXXXX) || exit
  trap 'rm -f "$datafile"; exit 1' HUP INT QUIT TERM PIPE
fi
if test -n "$datafile"; then
  add_env="$add_env MEMUSAGE_OUTPUT=$datafile"
fi
if test -n "$progname"; then
  add_env="$add_env MEMUSAGE_PROG_NAME=$progname"
fi
if test -n "$buffer"; then
  add_env="$add_env MEMUSAGE_BUFFER_SIZE=$buffer"
fi
if test -n "$notimer"; then
  add_env="$add_env MEMUSAGE_NO_TIMER=yes"
fi
if test -n "$mtrace"; then
  add_env="$add_env MEMUSAGE_MTRACE_FILE=$mtrace"
fi
if test -n "$tracemmap"; then
  add_env="$add_env MEMUSAGE_TRACE_MMAP=yes"
fi

eval "$add_env" '"$@"'
result=$?

if test -n "$png" -a -n "$datafile" -a -s "$datafile"; then
  case $png in *.png) ;; *) png="$png.png" ;; esac
  if command -v memusagestat >/dev/null 2>&1; then
    memusagestat $memusagestat_args "$datafile" "$png"
  else
    echo "Warning: memusagestat not found, PNG generation skipped." >&2
  fi
fi

if test -z "$data" -a -n "$datafile"; then rm -f "$datafile"; fi
exit $result